[project]
name = "web-scraper"
version = "0.1.0"
description = "UPA project web scraper"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
web-scraper = "main:main"
